name: GitHub Package
on:
  push:
    tags:
      - "v*"
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Run Maven tests
        run: mvn test

  deploy:
    name: Deploy to GitHub Packages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -X deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
